require('dotenv').config()

// SERVER
const PORT = process.env.PORT || 3003

// TROPIPAY TEST
const TROPIPAY_TESTING_EMAIL = process.env.TROPIPAY_TESTING_EMAIL
const TROPIPAY_TESTING_PASSWORD = process.env.TROPIPAY_TESTING_PASSWORD

module.exports = {
  PORT,
  TROPIPAY_TESTING_EMAIL,
  TROPIPAY_TESTING_PASSWORD,
}
